apiVersion: v1
kind: Namespace
metadata:
  name: dfgdfgdfg-staging
  labels:
    environment-id: env_87874c2f-ebf4-48b1-ac88-1b61854ac38a
    project-id: project_4df442d1-5908-4156-9a87-b98f25152643
    project-name: dfgdfgdfg
    environment-name: staging
    organization-id: org_9aad87d0-abbc-48f9-9038-002316f0475a
