apiVersion: v1
kind: Namespace
metadata:
  name: cvbncvb-dev
  labels:
    environment-id: env_5768e19e-e742-4dec-957a-0983b7a834d2
    project-id: project_62ab4aed-a9ae-47dd-be00-cab07e0c2c07
    project-name: cvbncvb
    environment-name: dev
    organization-id: org_1c58789b-c98c-4917-b321-116968ec4f8e
